name: Auto cancel
on:
    pull_request:
defaults:
    run:
        shell: bash
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 120
