name: Contexts
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_ACTOR: ${{ github.actor }}
        steps:
            - run: echo "${GITHUB_REPOSITORY} ${GITHUB_ACTOR}" 
