name: Status check
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
              env:
                    CONTEXT: ${{ toJson(github)}}
            - run: echo "Hello"
              if: ${{failure()}}
