name: Test
on:
  pull_request: # Triggers on pull request creation
    paths:
      - 'go/**/*.go' # Only triggers when Go files are changed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Step 1: Checkout
      - uses: actions/setup-go@v5  # Step 2: Setup Go environment
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go # Step 3: Run tests
